# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClockifyTui < Formula
  desc "A terminal user interface for Clockify"
  homepage "https://github.com/kevmul/clockify-tui"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kevmul/clockify-tui/releases/download/v0.0.1/clockify-tui_Darwin_x86_64.tar.gz"
      sha256 "7cb217fc2ec705b731b1779cb83ddd227ab6acd3147b041e55f2498947815a14"

      def install
        bin.install "clockify-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kevmul/clockify-tui/releases/download/v0.0.1/clockify-tui_Darwin_arm64.tar.gz"
      sha256 "9711243b94fdceeb3db33f6d60bd34364e9c5c865d138dfaefea542d499c5d63"

      def install
        bin.install "clockify-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevmul/clockify-tui/releases/download/v0.0.1/clockify-tui_Linux_x86_64.tar.gz"
      sha256 "ec30b3612741c6e06aee43255461c8e2ff0b751117c4bfeb12d36305db8bb98c"
      def install
        bin.install "clockify-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevmul/clockify-tui/releases/download/v0.0.1/clockify-tui_Linux_arm64.tar.gz"
      sha256 "7a615400cb46b056ba08c16742d8b6de569f5e1f7988afb94a257ac24f1e0508"
      def install
        bin.install "clockify-tui"
      end
    end
  end
end
